
import { supabase } from '@/integrations/supabase/client';

export interface SyncResult {
  action: string;
  lot_id: string;
  parcel_id: string;
  lot_name: string;
}

export const syncCadastralParcelsToLots = async (): Promise<SyncResult[]> => {
  try {
    console.log('🔄 Starting sync of PROPIEDAD parcels to lots...');
    
    const { data, error } = await supabase.rpc('sync_propiedad_parcels_to_lots');
    
    if (error) {
      console.error('❌ Error syncing parcels to lots:', error);
      throw error;
    }
    
    console.log(`✅ Sync completed. Results:`, data);
    return data || [];
  } catch (error) {
    console.error('❌ Unexpected error in syncCadastralParcelsToLots:', error);
    throw error;
  }
};

export const getAutoGeneratedLotsInfo = async () => {
  try {
    const { data, error } = await supabase
      .from('lots')
      .select(`
        id,
        name,
        auto_generated,
        source_parcel_id,
        cadastral_parcels!source_parcel_id(parcel_id, status)
      `)
      .eq('auto_generated', true);
    
    if (error) {
      console.error('❌ Error fetching auto-generated lots info:', error);
      throw error;
    }
    
    return data || [];
  } catch (error) {
    console.error('❌ Error in getAutoGeneratedLotsInfo:', error);
    throw error;
  }
};
