
import { supabase } from '@/integrations/supabase/client';

export interface SimpleSyncResult {
  lots_created: number;
  success: boolean;
  message: string;
}

export const syncCadastralParcelsToLots = async (): Promise<SimpleSyncResult> => {
  try {
    console.log('🔄 Starting simple sync of PROPIEDAD parcels to property lots...');
    
    // First check if we have any PROPIEDAD parcels
    const { data: parcelsCheck, error: parcelsError } = await supabase
      .from('cadastral_parcels')
      .select('id, parcel_id, status')
      .eq('status', 'PROPIEDAD');
    
    if (parcelsError) {
      console.error('❌ Error checking PROPIEDAD parcels:', parcelsError);
      throw parcelsError;
    }
    
    console.log(`📊 Found ${parcelsCheck?.length || 0} PROPIEDAD parcels before sync`);
    
    if (!parcelsCheck || parcelsCheck.length === 0) {
      console.warn('⚠️ No PROPIEDAD parcels found to sync');
      return {
        lots_created: 0,
        success: true,
        message: 'No PROPIEDAD parcels found to sync'
      };
    }
    
    // Call the database function to create property lots
    const { data, error } = await supabase.rpc('create_lots_from_propiedad_parcels');
    
    if (error) {
      console.error('❌ Database function error:', error);
      throw error;
    }
    
    console.log(`✅ Sync function executed successfully. Results:`, data);
    
    // Return the first (and only) result from the function
    if (data && data.length > 0) {
      const result = data[0];
      console.log(`📈 Created ${result.lots_created} property lots successfully`);
      return result;
    }
    
    return {
      lots_created: 0,
      success: true,
      message: 'No property lots were created'
    };
  } catch (error) {
    console.error('❌ Unexpected error in syncCadastralParcelsToLots:', error);
    throw error;
  }
};

export const getAutoGeneratedLotsInfo = async () => {
  try {
    console.log('🔍 Fetching auto-generated property lots info...');
    
    const { data, error } = await supabase
      .from('lots')
      .select(`
        id,
        name,
        auto_generated,
        lot_type,
        source_parcel_id,
        cadastral_parcels!source_parcel_id(parcel_id, status)
      `)
      .eq('auto_generated', true)
      .eq('lot_type', 'property');
    
    if (error) {
      console.error('❌ Error fetching auto-generated property lots info:', error);
      throw error;
    }
    
    console.log(`📊 Found ${data?.length || 0} auto-generated property lots`);
    return data || [];
  } catch (error) {
    console.error('❌ Error in getAutoGeneratedLotsInfo:', error);
    throw error;
  }
};
