
import React from 'react';
import { Button } from '@/components/ui/button';
import { Trash2, Square, Building, Leaf } from 'lucide-react';

interface SimplifiedPolygonControlsProps {
  onClearAll: () => void;
  selectedLotId: string | null;
  onDeleteSelected: () => void;
  polygonCount: number;
  lots: any[]; // Add lots to distinguish between types
}

const SimplifiedPolygonControls: React.FC<SimplifiedPolygonControlsProps> = ({
  onClearAll,
  selectedLotId,
  onDeleteSelected,
  polygonCount,
  lots = []
}) => {
  // Count property lots (auto-generated) and pasture lots (user-created)
  const propertyLots = lots.filter(lot => lot.autoGenerated === true);
  const pastureLots = lots.filter(lot => lot.autoGenerated !== true);
  
  return (
    <div className="absolute top-4 right-4 bg-white p-3 rounded-lg shadow-md border space-y-2">
      <div className="text-sm text-gray-600 space-y-1">
        <div className="flex items-center gap-2">
          <Building className="w-3 h-3 text-gray-500" />
          <span>Lotes de propiedad: {propertyLots.length}</span>
        </div>
        <div className="flex items-center gap-2">
          <Leaf className="w-3 h-3 text-green-500" />
          <span>Lotes de pastoreo: {pastureLots.length}</span>
        </div>
      </div>
      
      {selectedLotId && (
        <Button
          onClick={onDeleteSelected}
          size="sm"
          variant="destructive"
          className="w-full flex items-center gap-2"
        >
          <Trash2 className="w-4 h-4" />
          Eliminar Seleccionado
        </Button>
      )}
      
      {pastureLots.length > 0 && (
        <Button
          onClick={onClearAll}
          size="sm"
          variant="outline"
          className="w-full flex items-center gap-2"
        >
          <Square className="w-4 h-4" />
          Limpiar Pastoreo
        </Button>
      )}
    </div>
  );
};

export default SimplifiedPolygonControls;
