import React from 'react';
import LotCard from './LotCard';
import { type Lot } from '@/stores/lotStore';

interface LotsGridProps {
  lots: Lot[];
  onLotSelect: (lotId: string) => void;
  onDeleteLot: (lotId: string) => void;
  polygonData?: Array<{lotId: string; areaHectares?: number}>;
}

const LotsGrid: React.FC<LotsGridProps> = ({ 
  lots, 
  onLotSelect, 
  onDeleteLot,
  polygonData = []
}) => {
  const getPolygonArea = (lotId: string): number | undefined => {
    const polygon = polygonData.find(p => p.lotId === lotId);
    return polygon?.areaHectares;
  };

  return (
    <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 gap-6">
      {lots.map((lot) => (
        <LotCard
          key={lot.id}
          lot={{
            ...lot,
            autoGenerated: (lot as any).autoGenerated,
            sourceParcelId: (lot as any).sourceParcelId
          }}
          onSelect={onLotSelect}
          onDelete={onDeleteLot}
          polygonArea={getPolygonArea(lot.id)}
        />
      ))}
    </div>
  );
};

export default LotsGrid;
