
import React from 'react';
import { Card, CardContent } from '@/components/ui/card';
import { Badge } from '@/components/ui/badge';
import { MapPin, Zap, AlertCircle } from 'lucide-react';

interface SyncStatusCardProps {
  propiedadParcelsCount: number;
  autoGeneratedLotsCount: number;
}

const SyncStatusCard: React.FC<SyncStatusCardProps> = ({
  propiedadParcelsCount,
  autoGeneratedLotsCount
}) => {
  const canSync = propiedadParcelsCount > 0;
  const hasAutoLots = autoGeneratedLotsCount > 0;

  return (
    <Card className="border-l-4 border-l-blue-500">
      <CardContent className="pt-4">
        <div className="flex items-center justify-between">
          <div className="flex items-center space-x-3">
            <div className="flex items-center space-x-2">
              <MapPin className="w-4 h-4 text-blue-600" />
              <span className="text-sm font-medium">Parcelas PROPIEDAD:</span>
              <Badge variant={propiedadParcelsCount > 0 ? "default" : "secondary"}>
                {propiedadParcelsCount}
              </Badge>
            </div>
            <div className="flex items-center space-x-2">
              <Zap className="w-4 h-4 text-green-600" />
              <span className="text-sm font-medium">Lotes Auto-generados:</span>
              <Badge variant={autoGeneratedLotsCount > 0 ? "default" : "secondary"}>
                {autoGeneratedLotsCount}
              </Badge>
            </div>
          </div>
          
          {!canSync && (
            <div className="flex items-center space-x-2 text-amber-600">
              <AlertCircle className="w-4 h-4" />
              <span className="text-sm">Configure parcelas PROPIEDAD primero</span>
            </div>
          )}
        </div>
      </CardContent>
    </Card>
  );
};

export default SyncStatusCard;
