
import React from 'react';
import { Card, CardContent, CardHeader, CardTitle } from '@/components/ui/card';
import { Badge } from '@/components/ui/badge';
import { MapPin, Zap, Plus } from 'lucide-react';

interface WorkflowGuideProps {
  propiedadParcelsCount: number;
  autoGeneratedLotsCount: number;
  showGuide: boolean;
}

const WorkflowGuide: React.FC<WorkflowGuideProps> = ({
  propiedadParcelsCount,
  autoGeneratedLotsCount,
  showGuide
}) => {
  if (!showGuide) return null;

  return (
    <Card className="mb-6 border-blue-200 bg-blue-50">
      <CardHeader className="pb-3">
        <CardTitle className="text-lg flex items-center gap-2">
          <MapPin className="w-5 h-5 text-blue-600" />
          Flujo de Trabajo Recomendado
        </CardTitle>
      </CardHeader>
      <CardContent className="space-y-4">
        <div className="grid grid-cols-1 md:grid-cols-3 gap-4">
          <div className="flex items-start space-x-3">
            <div className="flex-shrink-0 w-8 h-8 bg-blue-600 text-white rounded-full flex items-center justify-center text-sm font-bold">
              1
            </div>
            <div>
              <h4 className="font-medium text-gray-900">Configurar Parcelas</h4>
              <p className="text-sm text-gray-600">Ve al "Mapa Catastral" y marca parcelas como "PROPIEDAD"</p>
              <Badge variant="outline" className="mt-1">
                {propiedadParcelsCount} parcelas PROPIEDAD
              </Badge>
            </div>
          </div>
          
          <div className="flex items-start space-x-3">
            <div className="flex-shrink-0 w-8 h-8 bg-green-600 text-white rounded-full flex items-center justify-center text-sm font-bold">
              2
            </div>
            <div>
              <h4 className="font-medium text-gray-900">Sincronizar Automáticamente</h4>
              <p className="text-sm text-gray-600">Usa "Sincronizar Catastral" para generar lotes automáticamente</p>
              <Badge variant="outline" className="mt-1">
                {autoGeneratedLotsCount} lotes auto-generados
              </Badge>
            </div>
          </div>
          
          <div className="flex items-start space-x-3">
            <div className="flex-shrink-0 w-8 h-8 bg-purple-600 text-white rounded-full flex items-center justify-center text-sm font-bold">
              3
            </div>
            <div>
              <h4 className="font-medium text-gray-900">Crear Lotes Adicionales</h4>
              <p className="text-sm text-gray-600">Usa "Crear Lote Manual" solo para lotes que no vienen de parcelas</p>
            </div>
          </div>
        </div>
      </CardContent>
    </Card>
  );
};

export default WorkflowGuide;
